### ISSUE TITLE
Parameters validation

### ISSUE THREAD

**Issue by Samuel-Bie** [franciskisiara/osmose#10]
This is not a issue, i just wanted to know if this package also validates the inputs?

**Comment by franciskisiara** [comment]
Hi @Samuel-Bie, I am not sure about your context with regards to validation but lets take a look at three examples

1. **Validating input to ensure they meet certain criteria** e.g required, size or an integer. In this case, the answer is **NO** because [laravel validation](https://laravel.com/docs/7.x/validation) is already quite comprehensive and powerful.

2. **Validating against column names to ensure the parameters passed match column names**. Again this is a **NO** because laravel already provides [exception handling](https://laravel.com/docs/7.x/errors) and I wouldn't want this package to deviate from the convention when displaying errors.

3. **Validating against conflicting internal methods** e.g using [bound()](https://github.com/franciskisiara/osmose#the-bound-method) method as well as [residue()](https://github.com/franciskisiara/osmose#defining-osmose-filters) to filter the same column in one filter class. **YES** it does. residue() will mostly takes precedence in this case - but that depends in part with the residue structure.

Nonetheless, I appreciate you taking an interest in this package and I hope you find it useful when writing reusable laravel code that scales well. If you have any questions, do not hesitate to ask.

**Comment by Samuel-Bie** [comment]
@franciskisiara  So it means that any validation regarding to the inputs that are passed to this package shoud be implemented by ourselves.

Make sense, i just wanted to know if i shoud leave it to the package or handle it.

The guy on this video shows some vulnerabilities regarding to the validation.

https://www.youtube.com/watch?v=kKGGVGiq2y8&list=PLMdXHJK-lGoDhWZ6YJW5B79CDoHWZwDN1&index=1

**Comment by franciskisiara** [comment]
Yeah, security should never be an afterthought when building applications.

Anyway, I will close this now, so that anyone looking for reference or help doesn't get entangled on discussions that dont directly help them resolve their issue.
